on:
 push:
  branches:
  - main
  - feature/*

jobs:
 job: 
   name: Test
   runs-on: self-hosted
   steps:
   - name: Checkout
     uses: actions/checkout@v5.0.0
   - name: Install Dependencies
     run: cd environment/dev
   - name: Terraform init
     run: terraform init
